function xdot = arm_ode(t, x, tau_func, p)
% arm_ode.m
% =========================================================================
% ODE right-hand side for the N-link planar robotic arm.
% Implements:   M(q)*qddot + C(q,qdot)*qdot + G(q) = tau(t)
% Rearranged:   qddot = M(q)^{-1} * [tau(t) - C(q,qdot)*qdot - G(q)]
%
% INPUTS:
%   t         – current time [s]
%   x         – [2N×1] state vector: [q; qdot]
%   tau_func  – function handle tau_func(t,q,qdot) → [N×1] joint torques
%               Pass @(t,x,xd) zeros(N,1) for free (unactuated) motion.
%   p         – parameter struct from params.m
%
% OUTPUT:
%   xdot      – [2N×1] state derivative: [qdot; qddot]
%
% NOTE: M_func, C_func, G_func must be on the MATLAB path (generated by
%       derive_dynamics.m). If they are not present, a fallback numerical
%       approximation using finite differences is NOT provided – run
%       derive_dynamics first.
% =========================================================================

N    = p.N;
q    = x(1:N);
qdot = x(N+1:2*N);

%% ── Evaluate dynamics matrices ───────────────────────────────────────────
M = M_func(q);
C = C_func(q, qdot);
G = G_func(q);

%% ── Evaluate control torques ─────────────────────────────────────────────
tau = tau_func(t, q, qdot);

%% ── Solve for joint accelerations ────────────────────────────────────────
% Use backslash (LU solve) rather than inv() for numerical stability
qddot = M \ (tau - C*qdot - G);

%% ── Assemble state derivative ────────────────────────────────────────────
xdot = [qdot; qddot];

end
