function C = C_func(in1,in2)
%C_func
%    C = C_func(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    12-May-2026 09:53:14

q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
qdot1 = in2(1,:);
qdot2 = in2(2,:);
qdot3 = in2(3,:);
qdot4 = in2(4,:);
t2 = sin(q2);
t3 = sin(q3);
t4 = sin(q4);
t5 = q2+q3;
t6 = q3+q4;
t11 = qdot1+qdot2+qdot3+qdot4;
t7 = t4.*6.0;
t8 = q4+t5;
t9 = sin(t5);
t10 = sin(t6);
t15 = t2.*(3.57e+2./1.0e+3);
t16 = t3.*1.365e-1;
t17 = t4.*2.31e-2;
t21 = qdot4.*t4.*(-2.31e-2);
t12 = sin(t8);
t13 = t10.*7.0;
t14 = t9.*(3.9e+1./2.5e+2);
t18 = qdot3.*t17;
t22 = t10.*2.695e-2;
t20 = t12.*3.08e-2;
t23 = t16+t22;
t24 = t17+t22;
t25 = qdot1.*t23;
t26 = qdot2.*t23;
t27 = qdot3.*t23;
t28 = qdot2.*t24;
t29 = qdot4.*t24;
t32 = t14+t15+t20;
t36 = t20+t24;
t39 = t14+t20+t23;
t30 = -t27;
t31 = -t29;
t33 = qdot1.*t32;
t34 = qdot2.*t32;
t37 = qdot4.*t36;
t40 = qdot1.*t39;
t41 = qdot3.*t39;
t35 = -t34;
t38 = -t37;
t42 = -t41;
C = reshape([t35+t38+t42,t30+t31+t33,t21+t26+t40,t18+t28+qdot1.*t36,-t33+t35+t38+t42,t30+t31,t21+t25+t26,t18+t28+qdot1.*t24,t38-t40+t42-qdot2.*t39,-t25-t26+t30+t31,t21,t17.*(qdot1+qdot2+qdot3),t11.*(t7+t12.*8.0+t13).*(-3.85e-3),t11.*(t7+t13).*(-3.85e-3),t4.*t11.*(-2.31e-2),0.0],[4,4]);
end
