function com_pos = com_positions_func(in1)
%COM_POSITIONS_FUNC
%    COM_POS = COM_POSITIONS_FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    12-May-2026 09:53:14

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
t2 = cos(q1);
t3 = sin(q1);
t4 = q1+q2;
t5 = cos(t4);
t6 = q3+t4;
t7 = sin(t4);
t11 = t2.*(2.0./5.0);
t12 = t3.*(2.0./5.0);
t8 = cos(t6);
t9 = q4+t6;
t10 = sin(t6);
t13 = t5.*(7.0./2.0e+1);
t14 = t7.*(7.0./2.0e+1);
com_pos = reshape([t2./5.0,t3./5.0+1.0,t5.*(7.0./4.0e+1)+t11,t7.*(7.0./4.0e+1)+t12+1.0,t8.*(3.0./2.0e+1)+t11+t13,t10.*(3.0./2.0e+1)+t12+t14+1.0,t8.*(3.0./1.0e+1)+t11+t13+cos(t9)./2.5e+1,t10.*(3.0./1.0e+1)+t12+t14+sin(t9)./2.5e+1+1.0],[2,4]);
end
