function G_vec = G_func(in1)
%G_func
%    G_vec = G_func(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    12-May-2026 09:53:14

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
t2 = q1+q2;
t3 = cos(t2);
t4 = q3+t2;
t5 = cos(t4);
t6 = q4+t4;
t8 = t3.*8.755425;
t7 = cos(t6);
t9 = t5.*3.8259;
t10 = t7.*7.5537e-1;
G_vec = [t8+t9+t10+cos(q1).*1.68732e+1;t8+t9+t10;t9+t10;t10];
end
