function M = M_func(in1)
%M_func
%    M = M_func(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    12-May-2026 09:53:14

q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
t2 = cos(q2);
t3 = cos(q3);
t4 = cos(q4);
t5 = q2+q3;
t6 = q3+q4;
t7 = cos(t5);
t8 = cos(t6);
t9 = q4+t5;
t12 = t3.*(2.73e+2./1.0e+3);
t13 = t2.*(3.57e+2./1.0e+3);
t14 = t3.*1.365e-1;
t15 = t4.*4.62e-2;
t16 = t4.*2.31e-2;
t10 = cos(t9);
t11 = t7.*(3.9e+1./2.5e+2);
t18 = t8.*5.39e-2;
t19 = t8.*2.695e-2;
t20 = t16+1.209e-2;
t17 = t10.*3.08e-2;
t21 = t19+t20;
t22 = t14+t15+t19+1.1409e-1;
t23 = t17+t21;
t24 = t11+t17+t22;
t25 = t11+t12+t13+t15+t17+t18+3.9584e-1;
M = reshape([t2.*(3.57e+2./5.0e+2)+t7.*(3.9e+1./1.25e+2)+t10.*6.16e-2+t12+t15+t18+1.030506666666667,t25,t24,t23,t25,t12+t15+t18+3.9584e-1,t22,t21,t24,t22,t15+1.1409e-1,t20,t23,t21,t20,1.209e-2],[4,4]);
end
