function p_obj = obj_com_position_func(in1)
%OBJ_COM_POSITION_FUNC
%    P_OBJ = OBJ_COM_POSITION_FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    12-May-2026 09:53:15

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
t2 = q1+q2;
t3 = q3+t2;
t4 = q4+t3;
p_obj = [cos(q1).*(2.0./5.0)+cos(t2).*(7.0./2.0e+1)+cos(t3).*(3.0./1.0e+1)+cos(t4).*(1.3e+1./1.0e+2);sin(q1).*(2.0./5.0)+sin(t2).*(7.0./2.0e+1)+sin(t3).*(3.0./1.0e+1)+sin(t4).*(1.3e+1./1.0e+2)+1.0];
end
