function T = T_func(in1,in2)
%T_func
%    T = T_func(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    12-May-2026 09:53:14

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
qdot1 = in2(1,:);
qdot2 = in2(2,:);
qdot3 = in2(3,:);
qdot4 = in2(4,:);
t2 = cos(q1);
t3 = sin(q1);
t4 = q1+q2;
t5 = qdot1.^2;
t6 = cos(t4);
t7 = q3+t4;
t8 = sin(t4);
t12 = t2.*(2.0./5.0);
t13 = t3.*(2.0./5.0);
t9 = cos(t7);
t10 = q4+t7;
t11 = sin(t7);
t16 = t6.*(7.0./2.0e+1);
t17 = t8.*(7.0./2.0e+1);
t14 = cos(t10);
t15 = sin(t10);
t18 = t9.*(3.0./1.0e+1);
t19 = t9.*(3.0./2.0e+1);
t20 = t11.*(3.0./1.0e+1);
t21 = t11.*(3.0./2.0e+1);
t22 = t14./2.5e+1;
t23 = t15./2.5e+1;
t24 = t14.*(1.3e+1./1.0e+2);
t25 = t15.*(1.3e+1./1.0e+2);
et1 = t5./7.5e+1+(qdot1+qdot2+qdot3).^2.*(3.0./8.0e+2)+(qdot2.*t6.*(7.0./4.0e+1)+qdot1.*(t6.*(7.0./4.0e+1)+t12)).^2.*(3.0./4.0)+(qdot2.*t8.*(7.0./4.0e+1)+qdot1.*(t8.*(7.0./4.0e+1)+t13)).^2.*(3.0./4.0)+(qdot1+qdot2+qdot3+qdot4).^2.*1.58e-3+(qdot1+qdot2).^2.*7.65625e-3+(t2.^2.*t5)./2.5e+1+(t3.^2.*t5)./2.5e+1+(qdot2.*(t16+t19)+qdot3.*t19+qdot1.*(t12+t16+t19)).^2./2.0+(qdot2.*(t17+t21)+qdot3.*t21+qdot1.*(t13+t17+t21)).^2./2.0+(qdot1.*(t12+t16+t18+t22)+qdot3.*(t18+t22)+qdot4.*t22+qdot2.*(t16+t18+t22)).^2.*(3.0./2.0e+1);
et2 = (qdot1.*(t12+t16+t18+t24)+qdot3.*(t18+t24)+qdot4.*t24+qdot2.*(t16+t18+t24)).^2./4.0+(qdot1.*(t13+t17+t20+t23)+qdot3.*(t20+t23)+qdot4.*t23+qdot2.*(t17+t20+t23)).^2.*(3.0./2.0e+1)+(qdot1.*(t13+t17+t20+t25)+qdot3.*(t20+t25)+qdot4.*t25+qdot2.*(t17+t20+t25)).^2./4.0;
T = et1+et2;
end
