function V = V_func(in1)
%V_func
%    V = V_func(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    12-May-2026 09:53:14

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
t2 = q1+q2;
t3 = q3+t2;
V = sin(q4+t3).*7.5537e-1+sin(q1).*1.68732e+1+sin(t2).*8.755425+sin(t3).*3.8259+5.1993e+1;
end
